// Example data for seeding the database
// Place this in scripts/seedData.js or similar

export const customers = [
  {
    id: 'CUST001',
    name: 'Acme Corp',
    email: 'contact@acme.com',
    phone: '555-1234',
    company: 'Acme Corp',
    industry: 'Retail',
    taxId: '12-3456789',
    billingAddress: '123 Main St, City, State',
    nameLower: 'acme corp',
    emailLower: 'contact@acme.com',
    status: 'Active',
  },
  {
    id: 'CUST002',
    name: 'Beta LLC',
    email: 'info@beta.com',
    phone: '555-5678',
    company: 'Beta LLC',
    industry: 'Logistics',
    taxId: '98-7654321',
    billingAddress: '456 Market Ave, City, State',
    nameLower: 'beta llc',
    emailLower: 'info@beta.com',
    status: 'Active',
  },
];

export const carriers = [
  {
    id: 'cr-mock-1',
    name: 'Prime Logistics',
    mcNumber: 'MC123456',
    taxId: '12-3456789',
    email: 'ops@primelogistics.com',
    phone: '(555) 100-1000',
    paymentTerms: 'Net 30',
    insuranceExpiry: new Date('2026-12-31'),
    status: 'Active',
    nameLower: 'prime logistics',
    mcNumberNormalized: '123456',
  },
  {
    id: 'cr-mock-2',
    name: 'Swift Haulers',
    mcNumber: 'MC234567',
    taxId: '23-4567890',
    email: 'ops@swifthaulers.com',
    phone: '(555) 200-2000',
    paymentTerms: 'Net 15',
    insuranceExpiry: new Date('2026-09-30'),
    status: 'Active',
    nameLower: 'swift haulers',
    mcNumberNormalized: '234567',
  },
  {
    id: 'cr-mock-3',
    name: 'Eagle Transport',
    mcNumber: 'MC345678',
    taxId: '34-5678901',
    email: 'ops@eagletransport.com',
    phone: '(555) 300-3000',
    paymentTerms: 'Net 45',
    insuranceExpiry: new Date('2027-03-31'),
    status: 'Active',
    nameLower: 'eagle transport',
    mcNumberNormalized: '345678',
  },
];

export const invoices = [
  {
    id: 'INV001',
    type: 'AR',
    customerId: 'CUST001',
    carrierId: 'cr-mock-1',
    customerName: 'Acme Corp',
    carrierName: 'Prime Logistics',
    carrier: 'Prime Logistics',
    invoiceNumber: '1001',
    amount: 1200.00,
    accessorials: 50.00,
    fuelSurcharge: 30.00,
    contractRate: 1120.00,
    status: 'pending',
    dueDate: new Date('2026-03-01'),
    issueDate: new Date('2026-02-01'),
    paymentTerms: 'Net 30',
  },
];

export const exceptions = [
  {
    id: 'EXC001',
    invoiceId: 'INV001',
    invoiceNumber: '1001',
    customerId: 'CUST001',
    customer: 'Acme Corp',
    carrierId: 'cr-mock-1',
    carrier: 'Prime Logistics',
    amount: 50.00,
    type: 'financial',
    reason: 'Accessorial charge mismatch',
    description: 'Accessorial charge exceeds contract rate',
    code: 'ACC_CHARGE_MISMATCH',
    message: 'Accessorial charge exceeds contract rate',
    severity: 'medium',
    status: 'Open',
  },
];

export const drivers = [
  {
    id: 'drv-mock-1',
    name: 'James Rivera',
    nameLower: 'james rivera',
    licenseNumber: 'DL-100001',
    phone: '(555) 401-1001',
    carrierId: 'cr-mock-1',
    licenseExpiry: new Date('2027-06-30'),
    status: 'Active',
  },
  {
    id: 'drv-mock-2',
    name: 'Maria Chen',
    nameLower: 'maria chen',
    licenseNumber: 'DL-100002',
    phone: '(555) 401-1002',
    carrierId: 'cr-mock-2',
    licenseExpiry: new Date('2026-11-30'),
    status: 'Active',
  },
  {
    id: 'drv-mock-3',
    name: 'Tony Okafor',
    nameLower: 'tony okafor',
    licenseNumber: 'DL-100003',
    phone: '(555) 401-1003',
    carrierId: 'cr-mock-3',
    licenseExpiry: new Date('2028-01-31'),
    status: 'Active',
  },
];

export const vehicles = [
  {
    id: 'veh-mock-1',
    unitNumber: 'TRK-001',
    type: 'Truck',
    make: 'Freightliner',
    model: 'Cascadia',
    year: 2022,
    vin: '1FUJHHDR4NLAA0001',
    licensePlate: 'TX-TRK001',
    carrierId: 'cr-mock-1',
    status: 'Active',
  },
  {
    id: 'veh-mock-2',
    unitNumber: 'TRK-002',
    type: 'Truck',
    make: 'Peterbilt',
    model: '579',
    year: 2021,
    vin: '1XPBDP9X3MD570002',
    licensePlate: 'TX-TRK002',
    carrierId: 'cr-mock-2',
    status: 'Active',
  },
  {
    id: 'veh-mock-3',
    unitNumber: 'VAN-001',
    type: 'Van',
    make: 'Mercedes-Benz',
    model: 'Sprinter',
    year: 2023,
    vin: 'WD4PF0CD1KP160003',
    licensePlate: 'TX-VAN003',
    carrierId: 'cr-mock-3',
    status: 'Active',
  },
];

export const trips = [
  {
    id: 'trip-mock-1',
    loadId: 'load-mock-1',
    driverId: 'drv-mock-1',
    vehicleId: 'veh-mock-1',
    origin: 'Dallas, TX',
    destination: 'Houston, TX',
    departureDate: new Date('2026-03-01'),
    arrivalDate: new Date('2026-03-02'),
    mileage: 239,
    status: 'Completed',
    notes: '',
  },
  {
    id: 'trip-mock-2',
    loadId: 'load-mock-2',
    driverId: 'drv-mock-2',
    vehicleId: 'veh-mock-2',
    origin: 'Houston, TX',
    destination: 'San Antonio, TX',
    departureDate: new Date('2026-03-05'),
    arrivalDate: new Date('2026-03-05'),
    mileage: 197,
    status: 'In Progress',
    notes: '',
  },
  {
    id: 'trip-mock-3',
    loadId: 'load-mock-3',
    driverId: 'drv-mock-3',
    vehicleId: 'veh-mock-3',
    origin: 'Austin, TX',
    destination: 'Dallas, TX',
    departureDate: new Date('2026-03-10'),
    arrivalDate: null,
    mileage: 195,
    status: 'Planned',
    notes: '',
  },
];
